version: '2'
services:
  kibana:
    image: danjellz/kibana:1.0
    volumes:
      - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: on-failure

  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
        - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    restart: on-failure


volumes:
  elasticsearch_data:
    driver: local
